app = "<mastodon-example>"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  LOCAL_DOMAIN = "<mastodon-example>.fly.dev"
  RAILS_ENV = "production"
  RAILS_LOG_TO_STDOUT = "enabled"
  WEB_CONCURRENCY = "1"

[processes]
  rails = "bundle exec rails s -p 8080"
  sidekiq = "bundle exec sidekiq"

[[statics]]
  guest_path = "/opt/mastodon/public"
  url_prefix = "/"

[[services]]
  internal_port = 8080
  processes = ["rails"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    path = "/health"
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
